import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import NextTopLoader from "nextjs-toploader";
import SmoothScrollProvider from "@/components/ui/provider/SmoothScrollprovider";

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair-display",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Elysia",
  description: "Generated by create next app",
  icons: {
    icon: "/fav.svg",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(playfairDisplay.variable, inter.variable)}>
      <body className="font-playfair antialiased">
        <NextTopLoader color="#007066" height={3} showSpinner={false} />
          <SmoothScrollProvider>{children}</SmoothScrollProvider>
       
      </body>
    </html>
  );
}
